{{- range $name, $secret := .Values.secrets }}
{{- if $secret.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $secret.target }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  refreshInterval: {{ $secret.refreshInterval | default "1h" }}
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ $secret.target }}
  data:
  {{- range $secret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ .remoteRef.key }}
        metadataPolicy: None
        property: {{ .remoteRef.property }}
  {{- end }}
{{- end }}
{{- end }}
