apiVersion: project.harbor.crossplane.io/v1alpha1
kind: Project
metadata:
  name: pnats
  labels:
    app.kubernetes.io/part-of: pnats-ci
spec:
  forProvider:
    name: pnats
    public: false
    vulnerabilityScanning: true
    storageQuota: 50
  providerConfigRef:
    name: default
