apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: harbor-robot-pnats-ci-push
  namespace: crossplane-system
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    secret:
      name: harbor-robot-pnats-ci
  data:
    - match:
        secretKey: token
        remoteRef:
          remoteKey: applications/developer-platform/harbor/robot
          property: password
