apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-gateway.yaml
  - auth-service.yaml
  - backend-main.yaml
  - integrations-service.yaml
  - mailer.yaml
  - web.yaml
  - pi-analysis.yaml
  - pi-scrape.yaml
  - pi-mailsum.yaml
  - boolgen-generator.yaml
  - boolgen-parser.yaml
  - boolgen-validator.yaml
  - boolgen-orchestrator.yaml
  - tasks.yaml
  - reminders.yaml
  - audit-api.yaml
  - audit-cdc.yaml
  - audit-timeline.yaml

commonLabels:
  app.kubernetes.io/part-of: pnats
