apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  namespace: argo-events
spec:
  jetstream:
    version: {{ .Values.eventBus.jetstream.version | quote }}
    replicas: {{ .Values.eventBus.jetstream.replicas }}
    persistence:
      storageClassName: {{ .Values.eventBus.jetstream.persistence.storageClassName }}
      accessMode: {{ .Values.eventBus.jetstream.persistence.accessMode }}
      volumeSize: {{ .Values.eventBus.jetstream.persistence.volumeSize }}
