apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github-webhook
  namespace: argo-events
spec:
  service:
    ports:
      - port: {{ .Values.github.webhookPort | int }}
        targetPort: {{ .Values.github.webhookPort | int }}
  github:
    pnow-ats-v2:
      repositories:
        - owner: {{ .Values.github.owner }}
          names:
            - {{ .Values.github.repo }}
      webhook:
        endpoint: {{ .Values.github.webhookEndpoint }}
        port: {{ .Values.github.webhookPort | quote }}
        method: POST
        url: {{ .Values.github.webhookUrl }}
      events:
        - pull_request
        - push
      apiToken:
        name: github-token
        key: token
      webhookSecret:
        name: github-webhook-secret
        key: secret
      contentType: json
      active: true
