{{- range $name, $secret := .Values.secrets }}
{{- if $secret.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $secret.target }}
  {{- if $secret.namespace }}
  namespace: {{ $secret.namespace }}
  {{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  refreshInterval: {{ $secret.refreshInterval | default "1h" }}
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ $secret.target }}
    {{- if $secret.template }}
    template:
      type: {{ $secret.template.type }}
    {{- end }}
  data:
  {{- range $secret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        property: {{ .remoteRef.property }}
  {{- end }}
{{- end }}
{{- end }}
