apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ci-workspace
spec:
  accessModes:
    - {{ .Values.workspace.accessMode }}
  storageClassName: {{ .Values.workspace.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.workspace.size }}
