apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pnats-staging
  namespace: pnats-staging
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: staging.pnats.cloud
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - staging.pnats.cloud
        - api-staging.pnats.cloud
      secretName: pnats-staging-tls
  rules:
    - host: staging.pnats.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 3000
    - host: api-staging.pnats.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 3000
