apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: keepalived
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: keepalived
    app.kubernetes.io/component: networking
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: keepalived
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keepalived
        app.kubernetes.io/component: networking
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      priorityClassName: system-node-critical
      serviceAccountName: keepalived
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: keepalived
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --log-detail
            - --dump-conf
          env:
            - name: KEEPALIVED_INTERFACE
              value: {{ .Values.vip.interface }}
            - name: KEEPALIVED_VIRTUAL_IPS
              value: {{ .Values.vip.address }}
            - name: KEEPALIVED_UNICAST_PEERS
              value: ""
            - name: KEEPALIVED_PASSWORD
              value: {{ .Values.vrrp.authPass }}
            - name: KEEPALIVED_PRIORITY
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KEEPALIVED_ROUTER_ID
              value: "{{ .Values.vrrp.routerId }}"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_BROADCAST
                - NET_RAW
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /container/service/keepalived/assets/keepalived.conf
              subPath: keepalived.conf
            - name: config
              mountPath: /etc/keepalived/check_kube_proxy.sh
              subPath: check_kube_proxy.sh
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pgrep keepalived
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pgrep keepalived
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: config
          configMap:
            name: keepalived-config
            defaultMode: 0755
