apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-token
  namespace: argo
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: github-token
  data:
    - secretKey: token
      remoteRef:
        key: secret/ci/github
        property: token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-token
  namespace: argo-events
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: github-token
  data:
    - secretKey: token
      remoteRef:
        key: secret/ci/github
        property: token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-webhook-secret
  namespace: argo-events
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: github-webhook-secret
  data:
    - secretKey: secret
      remoteRef:
        key: secret/ci/github
        property: secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-ssh-key
  namespace: argo
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: github-ssh-key
  data:
    - secretKey: ssh-privatekey
      remoteRef:
        key: secret/ci/github
        property: ssh-privatekey
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-docker-config
  namespace: argo
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: harbor-docker-config
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: secret/ci/harbor
        property: .dockerconfigjson
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-s3-creds
  namespace: argo
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argo-s3-creds
  data:
    - secretKey: access-key
      remoteRef:
        key: secret/ci/rook-ceph
        property: access-key
    - secretKey: secret-key
      remoteRef:
        key: secret/ci/rook-ceph
        property: secret-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack-webhook
  namespace: argo
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: slack-webhook
  data:
    - secretKey: url
      remoteRef:
        key: secret/ci/slack
        property: url
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-workflows-db
  namespace: argo
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argo-workflows-db
  data:
    - secretKey: username
      remoteRef:
        key: platform-data/postgres/argoworkflows
        property: username
    - secretKey: password
      remoteRef:
        key: platform-data/postgres/argoworkflows
        property: password
