apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pnats-production
  namespace: pnats
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: app.pnats.cloud
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.pnats.cloud
        - api.pnats.cloud
      secretName: pnats-production-tls
  rules:
    - host: app.pnats.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 3000
    - host: api.pnats.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 3000
