apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-pull-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: harbor-pull-secret
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "registry.pnats.cloud": {
                "username": "robot$pnats-ci-robot",
                "password": "{{ .password }}",
                "auth": "{{ printf "robot$pnats-ci-robot:%s" .password | b64enc }}"
              }
            }
          }
  data:
    - secretKey: password
      remoteRef:
        key: applications/developer-platform/harbor/robot
        property: password
